on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    strategy:
      matrix:
        prom-client-version: [11, 12, 13, 14]
    runs-on: ubuntu-latest
    name: Build with Prom Client ${{matrix.prom-client-version}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm i -D prom-client@${{matrix.prom-client-version}}
      - run: npm run build
